# -*- coding: utf-8 -*-
"""task11_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXGr77ZKFPQAVSsFpqlN_OONtJropNq7
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error
import pandas as pd

def car_price(file_name):
  data = pd.read_csv(file_name, index_col=0)

  predictors = ['Year', 'Engine HP', 'Engine Cylinders', 'highway MPG', 'city mpg', 'Popularity']
  target = data['MSRP']
  features = data[predictors]

  features = features.fillna(features.mean())
  features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.25, random_state=42)

  model = LinearRegression()
  model.fit(features_train, target_train)

  result = model.predict(features_test)
  rmse = root_mean_squared_error(target_test, result)

  dumb_model_result = [target_train.mean()] * len(target_test)
  dumb_rmse = root_mean_squared_error(target_test, dumb_model_result)

  print(f'RMSE модели: {rmse}')
  print(f'RMSE глупой модели: {dumb_rmse}')
  print(f'Разница между моделями: {dumb_rmse - rmse}')

car_price('/content/data.csv')